name: sc_pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scanpy=1.11.5
  - pandas=2.2.3
  - numpy=2.2.6
  - scipy=1.15
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - scikit-misc=0.5.2
  - umap-learn=0.5.7
  - leidenalg=0.11.0
  - python-igraph=1.0.0
  - pip
  - pip:
    - bbknn==1.6.0
    - fa2-modified==0.4
